# Generated by Django 4.0.5 on 2022-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Unknown', max_length=20, verbose_name='Имя автора')),
                ('email', models.EmailField(default='No Email', max_length=20, verbose_name='Эл. почта')),
                ('note', models.TextField(max_length=2000, verbose_name='Запись')),
                ('created_nt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_nt', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Список записей',
                'db_table': 'guestbook',
            },
        ),
    ]
